services:
  - type: web
    name: kobac-real-estate
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    branch: main
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        value: G-VY681TFKVE
      - key: PORT
        value: "3000"
